version: '3.8'

services:

  # FRONTEND SERVICE
  frontend:
    image: ghcr.io/schedool/frontend:latest
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
        NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL}
        NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL}
    container_name: schedool-frontend
    hostname: schedool-frontend
    ports:
      - '3065:3000'
    env_file: ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped

  # BACKEND SERVICE
  backend:
    image: ghcr.io/schedool/backend:latest
    build:
      context: ./backend
    container_name: schedool-backend
    hostname: schedool-backend
    ports:
      - '5080:5000'
    volumes:
      - ./backend/data:/backend/data
      - ./backend/logs:/backend/logs
    env_file: ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # POSTGRES SERVICE
  postgres:
    image: postgres:16-alpine
    container_name: schedool-postgres
    hostname: schedool-postgres
    env_file: ./backend/.env
    ports:
      - '5467:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U schedool -d schedool"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
