name: build_backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: docker login --username winsdominoes --password ${{ secrets.SCHEDOOL_ACTION_TOKEN }} ghcr.io

      - name: Build and push backend image
        run: |
          docker buildx build \
            -t ghcr.io/schedool/backend:latest \
            --push \
            ./backend
