name: build_backend_docker
on:
  schedule:
    - cron:
        "00 05 * * *" # build at 05:00 UTC every day

  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build Backend Docker Container
        env:
          SCHEDOOL_ACTION_TOKEN: ${{ secrets.SCHEDOOL_ACTION_TOKEN }}
        run: |
          docker login --username winsdominoes --password ${{ secrets.SCHEDOOL_ACTION_TOKEN }} ghcr.io
          docker buildx build -t ghcr.io/schedool/backend:latest .
          docker push ghcr.io/schedool/backend:latest
