// AUTO-GENERATED by scripts/generateScheduleData.mjs — DO NOT EDIT MANUALLY
// Re-run: node scripts/generateScheduleData.mjs

import {
    ScheduleItem,
    ScheduleData,
    FullDataset,
    DragPayload,
    EntityScheduleMap,
} from '../_types/schedule.types';

// Re-export for backward compatibility
export type { ScheduleItem, ScheduleData, DragPayload };

// ─── Dataset singleton ──────────────────────────────────────────────────────

let _dataset: FullDataset | null = null;
export function getFullDataset(): FullDataset {
    if (!_dataset) _dataset = generateFullScheduleDataset();
    return _dataset;
}
export function getTeacherSchedule(teacherCode: string): ScheduleData {
    return getFullDataset().teachers[teacherCode] ?? {};
}
export function getClassSchedule(classCode: string): ScheduleData {
    return getFullDataset().classes[classCode] ?? {};
}
export function getRoomSchedule(roomCode: string): ScheduleData {
    return getFullDataset().rooms[roomCode] ?? {};
}

// ─── Metadata ────────────────────────────────────────────────────────────────

export const TEACHER_CODES = [
    'T001', 'T002', 'T003', 'T004', 'T005', 'T006', 'T007', 'T008',
    'T009', 'T010', 'T011', 'T012', 'T013', 'T014', 'T015', 'T016',
    'T017', 'T018', 'T019', 'T020', 'T021', 'T022', 'T023', 'T024',
    'T025', 'T026', 'T027', 'T028', 'T029', 'T030', 'T031', 'T032',
    'T033', 'T034', 'T035', 'T036', 'T037', 'T038', 'T039', 'T040',
    'T041', 'T042', 'T043', 'T044', 'T045', 'T046', 'T047', 'T048',
    'T049', 'E001', 'E002', 'E003', 'E004', 'E005', 'E006', 'E007',
    'E008', 'E009', 'E010', 'E011', 'E012',
];

export const CLASS_CODES = [
    '1/1', '1/2', '1/3', '1/4', '2/1', '2/2', '2/3', '2/4',
    '3/1', '3/2', '3/3', '3/4', '4/1', '4/2', '4/3', '4/4',
    '4/5', '5/1', '5/2', '5/3', '5/4', '5/5', '6/1', '6/2',
    '6/3', '6/4', '6/5',
];

export const ROOM_CODES = [
    'A316', 'B101-102', 'B103', 'B104', 'B106', 'B107', 'B108-109', 'B210-211',
    'B212', 'B213', 'B215-216', 'B217', 'B218', 'C101-102', 'C103', 'C104',
    'C106', 'C107', 'C108-109', 'C210-211', 'C212', 'C213', 'C215-216', 'C217',
    'C218', 'D201', 'D202', 'D203', 'D204', 'D205', 'D206', 'D316',
    'D320', 'D321', 'D322', 'D323', 'D324', 'งานช่าง', 'นอกสถานที่',
];

export const TEACHER_META: Record<string, { prefix: string; firstName: string; lastName: string; department: string }> = {
    'T001': { prefix: '', firstName: 'รัตติยาวัลย์', lastName: '', department: '' },
    'T002': { prefix: '', firstName: 'สุทธิพจน์', lastName: '', department: '' },
    'T003': { prefix: '', firstName: 'พิรพงศ์', lastName: '', department: '' },
    'T004': { prefix: '', firstName: 'คณิตา', lastName: '', department: '' },
    'T005': { prefix: '', firstName: 'ภฤศรินทร์', lastName: '', department: '' },
    'T006': { prefix: '', firstName: 'ศรารัตน์', lastName: '', department: '' },
    'T007': { prefix: '', firstName: 'สหรัฐ', lastName: '', department: '' },
    'T008': { prefix: '', firstName: 'วสุพล', lastName: '', department: '' },
    'T009': { prefix: '', firstName: 'วงศ์ตะวัน', lastName: '', department: '' },
    'T010': { prefix: '', firstName: 'Coulter', lastName: '', department: '' },
    'T011': { prefix: '', firstName: 'นงค์นุช', lastName: '', department: '' },
    'T012': { prefix: '', firstName: 'พิมพ์วิภา', lastName: '', department: '' },
    'T013': { prefix: '', firstName: 'นิรมล', lastName: '', department: '' },
    'T014': { prefix: '', firstName: 'คชาภรณ์', lastName: '', department: '' },
    'T015': { prefix: '', firstName: 'พิไลลักษณ์', lastName: '', department: '' },
    'T016': { prefix: '', firstName: 'มนรวัส', lastName: '', department: '' },
    'T017': { prefix: '', firstName: 'สมใจ', lastName: '', department: '' },
    'T018': { prefix: '', firstName: 'วีรภัทร', lastName: '', department: '' },
    'T019': { prefix: '', firstName: 'สุธิโชติ', lastName: '', department: '' },
    'T020': { prefix: '', firstName: 'ธนิกานต์', lastName: '', department: '' },
    'T021': { prefix: '', firstName: 'ปาริชาติ', lastName: '', department: '' },
    'T022': { prefix: '', firstName: 'สุขุมาภรณ์', lastName: '', department: '' },
    'T023': { prefix: '', firstName: 'วิฑูรย์', lastName: '', department: '' },
    'T024': { prefix: '', firstName: 'รัชนิกร', lastName: '', department: '' },
    'T025': { prefix: '', firstName: 'มงคล', lastName: '', department: '' },
    'T026': { prefix: '', firstName: 'เมธา', lastName: '', department: '' },
    'T027': { prefix: '', firstName: 'พีรวัฒน์', lastName: '', department: '' },
    'T028': { prefix: '', firstName: 'จิดาภา', lastName: '', department: '' },
    'T029': { prefix: '', firstName: 'สุธีรวรรณ', lastName: '', department: '' },
    'T030': { prefix: '', firstName: 'สิปปนันท์', lastName: '', department: '' },
    'T031': { prefix: '', firstName: 'มารวย', lastName: '', department: '' },
    'T032': { prefix: '', firstName: 'พิชยา', lastName: '', department: '' },
    'T033': { prefix: '', firstName: 'จิรัสชยาณ์', lastName: '', department: '' },
    'T034': { prefix: '', firstName: 'เนตญา', lastName: '', department: '' },
    'T035': { prefix: '', firstName: 'ปาริชาต', lastName: '', department: '' },
    'T036': { prefix: '', firstName: 'วัชรพล', lastName: '', department: '' },
    'T037': { prefix: '', firstName: 'ธัญนัชญ์', lastName: '', department: '' },
    'T038': { prefix: '', firstName: 'ปริญญ์', lastName: '', department: '' },
    'T039': { prefix: '', firstName: 'หทัยรัตน์', lastName: '', department: '' },
    'T040': { prefix: '', firstName: 'ธนินทร์', lastName: '', department: '' },
    'T041': { prefix: '', firstName: 'อนันธิตา', lastName: '', department: '' },
    'T042': { prefix: '', firstName: 'อติวิชญ์', lastName: '', department: '' },
    'T043': { prefix: '', firstName: 'อานนท์', lastName: '', department: '' },
    'T044': { prefix: '', firstName: 'ณัฏฐ์ณภัทร', lastName: '', department: '' },
    'T045': { prefix: '', firstName: 'รุ่งนภา', lastName: '', department: '' },
    'T046': { prefix: '', firstName: 'วรวุฒิ', lastName: '', department: '' },
    'T047': { prefix: '', firstName: 'สุธาศินี', lastName: '', department: '' },
    'T048': { prefix: '', firstName: 'พฤกษ์', lastName: '', department: '' },
    'T049': { prefix: '', firstName: 'อติชาต', lastName: '', department: '' },
    'E001': { prefix: '', firstName: 'Falah', lastName: '', department: '' },
    'E002': { prefix: '', firstName: 'อรชุน', lastName: '', department: '' },
    'E003': { prefix: '', firstName: 'วัชระ', lastName: '', department: '' },
    'E004': { prefix: '', firstName: 'ภานุ', lastName: '', department: '' },
    'E005': { prefix: '', firstName: 'มหาลัย (วมว)', lastName: '', department: '' },
    'E006': { prefix: '', firstName: 'นฤเทพ', lastName: '', department: '' },
    'E007': { prefix: '', firstName: 'มยุรี', lastName: '', department: '' },
    'E008': { prefix: '', firstName: 'วินัย', lastName: '', department: '' },
    'E009': { prefix: '', firstName: 'บุญฤทธิ์', lastName: '', department: '' },
    'E010': { prefix: '', firstName: 'วรยศ', lastName: '', department: '' },
    'E011': { prefix: '', firstName: 'อิสระ', lastName: '', department: '' },
    'E012': { prefix: '', firstName: 'ฐิติวรดา', lastName: '', department: '' },
};

export const CLASS_META: Record<string, { defaultRoom: string; level: string }> = {
    '1/1': { defaultRoom: 'C103', level: 'ม.1' },
    '1/2': { defaultRoom: 'C104', level: 'ม.1' },
    '1/3': { defaultRoom: 'C106', level: 'ม.1' },
    '1/4': { defaultRoom: 'C107', level: 'ม.1' },
    '2/1': { defaultRoom: 'C212', level: 'ม.2' },
    '2/2': { defaultRoom: 'C213', level: 'ม.2' },
    '2/3': { defaultRoom: 'C217', level: 'ม.2' },
    '2/4': { defaultRoom: 'C218', level: 'ม.2' },
    '3/1': { defaultRoom: 'B103', level: 'ม.3' },
    '3/2': { defaultRoom: 'B104', level: 'ม.3' },
    '3/3': { defaultRoom: 'B106', level: 'ม.3' },
    '3/4': { defaultRoom: 'B107', level: 'ม.3' },
    '4/1': { defaultRoom: '', level: 'ม.4' },
    '4/2': { defaultRoom: '', level: 'ม.4' },
    '4/3': { defaultRoom: '', level: 'ม.4' },
    '4/4': { defaultRoom: '', level: 'ม.4' },
    '4/5': { defaultRoom: '', level: 'ม.4' },
    '5/1': { defaultRoom: '', level: 'ม.5' },
    '5/2': { defaultRoom: '', level: 'ม.5' },
    '5/3': { defaultRoom: '', level: 'ม.5' },
    '5/4': { defaultRoom: '', level: 'ม.5' },
    '5/5': { defaultRoom: '', level: 'ม.5' },
    '6/1': { defaultRoom: '', level: 'ม.6' },
    '6/2': { defaultRoom: '', level: 'ม.6' },
    '6/3': { defaultRoom: '', level: 'ม.6' },
    '6/4': { defaultRoom: '', level: 'ม.6' },
    '6/5': { defaultRoom: '', level: 'ม.6' },
};

export const ROOM_META: Record<string, { name: string; type: 'homeroom' | 'specialist' }> = {
    'A316': { name: 'A316', type: 'homeroom' },
    'B101-102': { name: 'เคมี', type: 'specialist' },
    'B103': { name: 'ม.3/1', type: 'homeroom' },
    'B104': { name: 'ม.3/2', type: 'homeroom' },
    'B106': { name: 'ม.3/3', type: 'homeroom' },
    'B107': { name: 'ม.3/4', type: 'homeroom' },
    'B108-109': { name: 'ชีววิทยา', type: 'specialist' },
    'B210-211': { name: 'ฟิสิกส์', type: 'specialist' },
    'B212': { name: 'B212', type: 'homeroom' },
    'B213': { name: 'B213', type: 'homeroom' },
    'B215-216': { name: 'คณิต', type: 'specialist' },
    'B217': { name: 'B217', type: 'homeroom' },
    'B218': { name: 'B218', type: 'homeroom' },
    'C101-102': { name: 'สังคม', type: 'specialist' },
    'C103': { name: 'ม.1/1', type: 'homeroom' },
    'C104': { name: 'ม.1/2', type: 'homeroom' },
    'C106': { name: 'ม.1/3', type: 'homeroom' },
    'C107': { name: 'ม.1/4', type: 'homeroom' },
    'C108-109': { name: 'ศิลปะ', type: 'specialist' },
    'C210-211': { name: 'อังกฤษ', type: 'specialist' },
    'C212': { name: 'ม.2/1', type: 'homeroom' },
    'C213': { name: 'ม.2/2', type: 'homeroom' },
    'C215-216': { name: 'ไทย', type: 'specialist' },
    'C217': { name: 'ม.2/3', type: 'homeroom' },
    'C218': { name: 'ม.2/4', type: 'homeroom' },
    'D201': { name: 'D201', type: 'homeroom' },
    'D202': { name: 'D202', type: 'homeroom' },
    'D203': { name: 'COM', type: 'specialist' },
    'D204': { name: 'COM', type: 'specialist' },
    'D205': { name: 'D205', type: 'homeroom' },
    'D206': { name: 'D206', type: 'homeroom' },
    'D316': { name: 'ยิม', type: 'specialist' },
    'D320': { name: 'D320', type: 'homeroom' },
    'D321': { name: 'นาฎศิลป์', type: 'specialist' },
    'D322': { name: 'ดนตรีไทย', type: 'specialist' },
    'D323': { name: 'ดนตรีสากล', type: 'specialist' },
    'D324': { name: 'D324', type: 'homeroom' },
    'งานช่าง': { name: 'งานช่าง', type: 'specialist' },
    'นอกสถานที่': { name: 'OUT', type: 'specialist' },
};

export interface SubjectInfo {
    code: string;
    name: string;
    variant: 'green' | 'red';
}

export const SUBJECTS: Record<string, SubjectInfo> = {
    'ท21102': { code: 'ท21102', name: 'ภาษาไทย2', variant: 'red' },
    'ว21103': { code: 'ว21103', name: 'วิทยาศาสตร์2', variant: 'green' },
    'ส21103': { code: 'ส21103', name: 'สังคมศึกษา2', variant: 'green' },
    'ส21104': { code: 'ส21104', name: 'ศาสนา1', variant: 'red' },
    'พ21102': { code: 'พ21102', name: 'สุขศึกษาและพลศึกษา2', variant: 'red' },
    'ศ21102': { code: 'ศ21102', name: 'ศิลปนาฏดุริยางค์2', variant: 'red' },
    'อ21102': { code: 'อ21102', name: 'ภาษาอังกฤษพื้นฐาน2', variant: 'red' },
    'ค21201': { code: 'ค21201', name: 'คณิตศาสตร์เพิ่มเติม1', variant: 'red' },
    'ค21202': { code: 'ค21202', name: 'คณิตศาสตร์เพิ่มเติม2', variant: 'red' },
    'ว21202': { code: 'ว21202', name: 'เส้นทางการเป็นนักวิทยาศาสตร์และนวัตกร', variant: 'red' },
    'อ21201': { code: 'อ21201', name: 'ภาษาอังกฤษเพื่อการสื่อสาร1', variant: 'green' },
    'ท22102': { code: 'ท22102', name: 'ภาษาไทย4', variant: 'red' },
    'ว22102': { code: 'ว22102', name: 'วิทยาศาสตร์4', variant: 'red' },
    'ส22103': { code: 'ส22103', name: 'สังคมศึกษา4', variant: 'green' },
    'ส22104': { code: 'ส22104', name: 'ประวัติศาสตร์', variant: 'red' },
    'พ22102': { code: 'พ22102', name: 'สุขศึกษาและพลศึกษา', variant: 'red' },
    'ศ22102': { code: 'ศ22102', name: 'ศิลปนาฏดุริยางค์4', variant: 'red' },
    'ง22101': { code: 'ง22101', name: 'เศรษฐกิจพอเพียง', variant: 'green' },
    'อ22102': { code: 'อ22102', name: 'ภาษาอังกฤษระดับกลาง2', variant: 'red' },
    'ค22201': { code: 'ค22201', name: 'คณิตศาสตร์เพิ่มเติม3', variant: 'red' },
    'ค22202': { code: 'ค22202', name: 'คณิตศาสตร์เพิ่มเติม4', variant: 'red' },
    'ว22202': { code: 'ว22202', name: 'โครงงานและนวัตกรรม2', variant: 'red' },
    'ว22203': { code: 'ว22203', name: 'ระบบสมองกลฝังตัวเบื้องต้น', variant: 'green' },
    'อ22202': { code: 'อ22202', name: 'ภาษาอังกฤษเพื่อการอภิปรายกลุ่ม', variant: 'red' },
    'ท23102': { code: 'ท23102', name: 'ภาษาในวรรณคดีไทย2', variant: 'red' },
    'ว23102': { code: 'ว23102', name: 'วิทยาศาสตร์6', variant: 'red' },
    'ว23103': { code: 'ว23103', name: 'วิทยาการคำนวณ3', variant: 'green' },
    'ส23104': { code: 'ส23104', name: 'สังคมศึกษา6', variant: 'red' },
    'พ23102': { code: 'พ23102', name: 'สุขศึกษาและพลศึกษา6', variant: 'red' },
    'ศ23102': { code: 'ศ23102', name: 'ศิลปนาฏดุริยางค์6', variant: 'red' },
    'อ23102': { code: 'อ23102', name: 'ภาษาอังกฤษบูรณาการ2', variant: 'red' },
    'ค23201': { code: 'ค23201', name: 'คณิตศาสตร์เพิ่มเติม5', variant: 'red' },
    'ง23202': { code: 'ง23202', name: 'ทักษะงานช่าง', variant: 'red' },
    'อ23202': { code: 'อ23202', name: 'พัฒนาคำศัพท์', variant: 'red' },
    'ท31102': { code: 'ท31102', name: 'ภาษาไทย2', variant: 'red' },
    'ค31102': { code: 'ค31102', name: 'ความสัมพันธ์และสถิติ', variant: 'red' },
    'ว31104': { code: 'ว31104', name: 'การออกแบบเรขศิลป์ด้วยคอมพิวเตอร์', variant: 'red' },
    'พ31102': { code: 'พ31102', name: 'สุขศึกษาและพลศึกษา2', variant: 'red' },
    'ศ31102': { code: 'ศ31102', name: 'ทัศนศิลป์และการออกแบบ', variant: 'red' },
    'อ31102': { code: 'อ31102', name: 'ภาษาอังกฤษขั้นกลาง', variant: 'red' },
    'ค31202': { code: 'ค31202', name: 'เรขาคณิตวิเคราะห์และฟังก์ชันตรีโกณมิติ', variant: 'red' },
    'ว31201': { code: 'ว31201', name: 'กลศาสตร์', variant: 'green' },
    'ว31221': { code: 'ว31221', name: 'ปริมาณสารสัมพันธ์', variant: 'green' },
    'ว31241': { code: 'ว31241', name: 'พันธุศาสตร์และวิวัฒนาการ', variant: 'green' },
    'ว31283': { code: 'ว31283', name: 'สัมมนาทางวิทยาศาสตร์', variant: 'green' },
    'ว31284': { code: 'ว31284', name: 'การเขียนโปรแกรมคอมพิวเตอร์2', variant: 'red' },
    'ท32102': { code: 'ท32102', name: 'ภาษาไทย4', variant: 'red' },
    'ค32102': { code: 'ค32102', name: 'ลำดับและอนุกรม', variant: 'red' },
    'ส32103': { code: 'ส32103', name: 'ภูมิศาสตร์', variant: 'green' },
    'พ32102': { code: 'พ32102', name: 'สุขศึกษาและพลศึกษา4', variant: 'red' },
    'ศ32101': { code: 'ศ32101', name: 'นาฏศิลป์และดนตรี', variant: 'green' },
    'อ32102': { code: 'อ32102', name: 'ภาษาอังกฤษบูรณาการ2', variant: 'red' },
    'ท32201': { code: 'ท32201', name: 'ภาษาไทยเพื่อการเขียนงานวิชาการ', variant: 'green' },
    'ค32202': { code: 'ค32202', name: 'แคลคูลัสเบื้องต้นและการประยุกต์', variant: 'red' },
    'ว32202': { code: 'ว32202', name: 'คลื่นแสง', variant: 'red' },
    'ว32222': { code: 'ว32222', name: 'กรด-เบสและเคมีไฟฟ้า', variant: 'red' },
    'ว32242': { code: 'ว32242', name: 'ความหลากหลายทางชีวภาพ', variant: 'red' },
    'ว32283': { code: 'ว32283', name: 'การสื่อสารวิทยาศาสตร์ในยุคดิจิทัล', variant: 'green' },
    'ท33102': { code: 'ท33102', name: 'คุณค่าของภาษาในวรรณคดีไทย2', variant: 'red' },
    'ว33103': { code: 'ว33103', name: 'ฟิสิกส์พื้นฐาน', variant: 'green' },
    'ส33102': { code: 'ส33102', name: 'ศาสนา3', variant: 'red' },
    'พ33102': { code: 'พ33102', name: 'สุขศึกษาและพลศึกษา6', variant: 'red' },
    'ว33242': { code: 'ว33242', name: 'สรีรวิทยาของมนุษย์และสัตว์ขั้นสูง', variant: 'red' },
    'อ33203': { code: 'อ33203', name: 'พัฒนาการอ่านและการเขียนภาษาอังกฤษเชิงบูรณาการ', variant: 'green' },
};

export const SUBJECT_ROOM_MAP: Record<string, string> = {
    'ศ21102': 'C108-109',
    'ศ22102': 'D323',
    'ว23103': 'D203',
    'พ23102': 'D316',
    'ง23202': 'งานช่าง',
    'ว31104': 'D203',
    'ศ31102': 'C108-109',
    'พ32102': 'C101-102',
    'ศ32101': 'D321',
    'ว32283': 'A316',
    'พ33102': 'D316',
};

export const generateScheduleItem = (): ScheduleItem => ({
    teacher: 'T001',
    teacherName: 'รัตติยาวัลย์',
    classCode: '1/1',
    room: 'C103',
    roomName: 'ม.1/1',
    subjectCode: 'ท21102',
    subject: 'ภาษาไทย2',
    variant: 'green',
});

type RawLesson = [teacher: string, subject: string, cls: string, room: string, day: string, slot: number];
const LESSONS: RawLesson[] = [];

export function generateFullScheduleDataset(): FullDataset {
    const teachers: EntityScheduleMap = {};
    const classes: EntityScheduleMap = {};
    const roomsMap: EntityScheduleMap = {};

    for (const [teacher, subject, cls, room, day, slot] of LESSONS) {
        const subjectInfo = SUBJECTS[subject];
        const item: ScheduleItem = {
            teacher,
            teacherName: TEACHER_META[teacher]?.firstName ?? teacher,
            classCode: cls,
            room,
            roomName: ROOM_META[room]?.name ?? room,
            subjectCode: subject,
            subject: subjectInfo?.name ?? subject,
            variant: subjectInfo?.variant ?? 'green',
        };
        if (!teachers[teacher]) teachers[teacher] = {};
        if (!teachers[teacher][day]) teachers[teacher][day] = {};
        teachers[teacher][day][slot] = item;
        if (!classes[cls]) classes[cls] = {};
        if (!classes[cls][day]) classes[cls][day] = {};
        classes[cls][day][slot] = item;
        if (!roomsMap[room]) roomsMap[room] = {};
        if (!roomsMap[room][day]) roomsMap[room][day] = {};
        roomsMap[room][day][slot] = item;
    }
    return { teachers, classes, rooms: roomsMap };
}

export interface WorkloadEntry {
    subjectCode: string;
    subject: string;
    variant: 'green' | 'red';
    assignments: { classCode: string; room: string; periodsPerWeek: number }[];
    totalPeriods: number;
}

export function computeTeacherWorkload(teacherCode: string): WorkloadEntry[] {
    return TEACHER_WORKLOAD[teacherCode] ?? [];
}

export const TEACHER_WORKLOAD: Record<string, WorkloadEntry[]> = {
    'E001': [
        {
            subjectCode: 'อ22202',
            subject: 'EFF2',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 1 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 1 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 1 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'อ23202',
            subject: 'EFF3',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 1 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 1 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 1 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'ว32283',
            subject: 'EFF5',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/2', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/3', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/4', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/5', room: 'A316', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
        {
            subjectCode: 'อ33203',
            subject: 'EFF6',
            variant: 'green',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 1 },
                { classCode: '6/2', room: '', periodsPerWeek: 1 },
                { classCode: '6/3', room: '', periodsPerWeek: 1 },
                { classCode: '6/4', room: '', periodsPerWeek: 1 },
                { classCode: '6/5', room: '', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'E002': [
        {
            subjectCode: 'ค31102',
            subject: 'ความสัมพันธ์และสถิติ',
            variant: 'red',
            assignments: [
                { classCode: '4/4', room: '', periodsPerWeek: 3 },
                { classCode: '4/5', room: '', periodsPerWeek: 3 },
            ],
            totalPeriods: 6,
        },
    ],
    'E003': [
        {
            subjectCode: 'ว31221',
            subject: 'ปริมาณสารสัมพันธ์',
            variant: 'green',
            assignments: [
                { classCode: '4/4', room: '', periodsPerWeek: 4 },
                { classCode: '4/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 8,
        },
    ],
    'E004': [
        {
            subjectCode: 'ค32102',
            subject: 'ลำดับและอนุกรม',
            variant: 'red',
            assignments: [
                { classCode: '5/4', room: '', periodsPerWeek: 2 },
                { classCode: '5/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 4,
        },
    ],
    'E005': [
        {
            subjectCode: 'ว32242',
            subject: 'ความหลากหลายทางชีวภาพ',
            variant: 'red',
            assignments: [
                { classCode: '5/4', room: '', periodsPerWeek: 4 },
                { classCode: '5/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 8,
        },
    ],
    'E006': [
        {
            subjectCode: 'พ31102',
            subject: 'สุขศึกษาและพลศึกษา2',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 1 },
                { classCode: '4/2', room: '', periodsPerWeek: 1 },
                { classCode: '4/3', room: '', periodsPerWeek: 1 },
                { classCode: '4/4', room: '', periodsPerWeek: 1 },
                { classCode: '4/5', room: '', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'E007': [
        {
            subjectCode: 'พ22102',
            subject: 'สุขศึกษาและพลศึกษา',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T001': [
        {
            subjectCode: 'ง22101',
            subject: 'เศรษฐกิจพอเพียง',
            variant: 'green',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ง23202',
            subject: 'ทักษะงานช่าง',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'งานช่าง', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'งานช่าง', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'งานช่าง', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'งานช่าง', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T002': [
        {
            subjectCode: 'ค32202',
            subject: 'แคลคูลัสเบื้องต้นและการประยุกต์',
            variant: 'red',
            assignments: [
                { classCode: '5/4', room: '', periodsPerWeek: 4 },
                { classCode: '5/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 8,
        },
    ],
    'T003': [
        {
            subjectCode: 'ค31202',
            subject: 'เรขาคณิตวิเคราะห์และฟังก์ชันตรีโกณมิติ',
            variant: 'red',
            assignments: [
                { classCode: '4/4', room: '', periodsPerWeek: 4 },
                { classCode: '4/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ว31283',
            subject: 'สัมมนาทางวิทยาศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/3', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
    ],
    'T004': [
        {
            subjectCode: 'ค23201',
            subject: 'คณิตศาสตร์เพิ่มเติม5',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T005': [
        {
            subjectCode: 'ค21201',
            subject: 'คณิตศาสตร์เพิ่มเติม1',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 3 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 3 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 3 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ค32102',
            subject: 'ลำดับและอนุกรม',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 2 },
                { classCode: '5/2', room: '', periodsPerWeek: 2 },
                { classCode: '5/3', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 6,
        },
    ],
    'T006': [
        {
            subjectCode: 'ค21202',
            subject: 'คณิตศาสตร์เพิ่มเติม2',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ว22202',
            subject: 'โครงงานและนวัตกรรม2',
            variant: 'red',
            assignments: [
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ค31202',
            subject: 'เรขาคณิตวิเคราะห์และฟังก์ชันตรีโกณมิติ',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 4 },
                { classCode: '4/2', room: '', periodsPerWeek: 4 },
                { classCode: '4/3', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 12,
        },
    ],
    'T007': [
        {
            subjectCode: 'ค32202',
            subject: 'แคลคูลัสเบื้องต้นและการประยุกต์',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 4 },
                { classCode: '5/2', room: '', periodsPerWeek: 4 },
                { classCode: '5/3', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 12,
        },
    ],
    'T008': [
        {
            subjectCode: 'ค22202',
            subject: 'คณิตศาสตร์เพิ่มเติม4',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ค31102',
            subject: 'ความสัมพันธ์และสถิติ',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 3 },
                { classCode: '4/2', room: '', periodsPerWeek: 3 },
                { classCode: '4/3', room: '', periodsPerWeek: 3 },
            ],
            totalPeriods: 9,
        },
    ],
    'T009': [
        {
            subjectCode: 'ค22201',
            subject: 'คณิตศาสตร์เพิ่มเติม3',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 3 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 3 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 3 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
    ],
    'T010': [
        {
            subjectCode: 'ค21201',
            subject: 'คณิตศาสตร์เพิ่มเติม1',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 3 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 3 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 3 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'อ21201',
            subject: 'EFF1',
            variant: 'green',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 1 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 1 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 1 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'ว31284',
            subject: 'EFF4',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 1 },
                { classCode: '4/2', room: '', periodsPerWeek: 1 },
                { classCode: '4/3', room: '', periodsPerWeek: 1 },
                { classCode: '4/4', room: '', periodsPerWeek: 1 },
                { classCode: '4/5', room: '', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'T011': [
        {
            subjectCode: 'ว21202',
            subject: 'เส้นทางการเป็นนักวิทยาศาสตร์และนวัตกร',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'ว31283',
            subject: 'สัมมนาทางวิทยาศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/4', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
    ],
    'T012': [
        {
            subjectCode: 'ว21202',
            subject: 'เส้นทางการเป็นนักวิทยาศาสตร์และนวัตกร',
            variant: 'red',
            assignments: [
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'ว23103',
            subject: 'วิทยาการคำนวณ3',
            variant: 'green',
            assignments: [
                { classCode: '3/1', room: 'D203', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'D203', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'D203', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'D203', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T013': [
        {
            subjectCode: 'ว31104',
            subject: 'การออกแบบเรขศิลป์ด้วยคอมพิวเตอร์',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: 'D203', periodsPerWeek: 2 },
                { classCode: '4/2', room: 'D203', periodsPerWeek: 2 },
                { classCode: '4/3', room: 'D203', periodsPerWeek: 2 },
                { classCode: '4/4', room: 'D203', periodsPerWeek: 2 },
                { classCode: '4/5', room: 'D203', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T014': [
        {
            subjectCode: 'ว22203',
            subject: 'ระบบสมองกลฝังตัวเบื้องต้น',
            variant: 'green',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ว31284',
            subject: 'การเขียนโปรแกรมคอมพิวเตอร์2',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 2 },
                { classCode: '4/2', room: '', periodsPerWeek: 2 },
                { classCode: '4/3', room: '', periodsPerWeek: 2 },
                { classCode: '4/4', room: '', periodsPerWeek: 2 },
                { classCode: '4/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T015': [
        {
            subjectCode: 'ว31221',
            subject: 'ปริมาณสารสัมพันธ์',
            variant: 'green',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 4 },
                { classCode: '4/2', room: '', periodsPerWeek: 4 },
                { classCode: '4/3', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 12,
        },
    ],
    'T016': [
        {
            subjectCode: 'ว21202',
            subject: 'เส้นทางการเป็นนักวิทยาศาสตร์และนวัตกร',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ว32283',
            subject: 'การสื่อสารวิทยาศาสตร์ในยุคดิจิทัล',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/2', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/3', room: 'A316', periodsPerWeek: 3 },
            ],
            totalPeriods: 9,
        },
    ],
    'T017': [
        {
            subjectCode: 'ว23102',
            subject: 'วิทยาศาสตร์6',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 3 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 3 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 3 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ว31283',
            subject: 'สัมมนาทางวิทยาศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
    ],
    'T018': [
        {
            subjectCode: 'ว22202',
            subject: 'โครงงานและนวัตกรรม2',
            variant: 'red',
            assignments: [
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ว32222',
            subject: 'กรด-เบสและเคมีไฟฟ้า',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 4 },
                { classCode: '5/2', room: '', periodsPerWeek: 4 },
                { classCode: '5/3', room: '', periodsPerWeek: 4 },
                { classCode: '5/4', room: '', periodsPerWeek: 4 },
                { classCode: '5/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 20,
        },
    ],
    'T019': [
        {
            subjectCode: 'ว22102',
            subject: 'วิทยาศาสตร์4',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 3 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 3 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 3 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ว33242',
            subject: 'สรีรวิทยาของมนุษย์และสัตว์ขั้นสูง',
            variant: 'red',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 2 },
                { classCode: '6/2', room: '', periodsPerWeek: 2 },
                { classCode: '6/3', room: '', periodsPerWeek: 2 },
                { classCode: '6/4', room: '', periodsPerWeek: 2 },
                { classCode: '6/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T020': [
        {
            subjectCode: 'ว31241',
            subject: 'พันธุศาสตร์และวิวัฒนาการ',
            variant: 'green',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 4 },
                { classCode: '4/2', room: '', periodsPerWeek: 4 },
                { classCode: '4/3', room: '', periodsPerWeek: 4 },
                { classCode: '4/4', room: '', periodsPerWeek: 4 },
                { classCode: '4/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 20,
        },
    ],
    'T021': [
        {
            subjectCode: 'ว22202',
            subject: 'โครงงานและนวัตกรรม2',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ว32283',
            subject: 'การสื่อสารวิทยาศาสตร์ในยุคดิจิทัล',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/2', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/3', room: 'A316', periodsPerWeek: 3 },
            ],
            totalPeriods: 9,
        },
    ],
    'T022': [
        {
            subjectCode: 'ว31283',
            subject: 'สัมมนาทางวิทยาศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/2', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ว32242',
            subject: 'ความหลากหลายทางชีวภาพ',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 4 },
                { classCode: '5/2', room: '', periodsPerWeek: 4 },
                { classCode: '5/3', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 12,
        },
    ],
    'T023': [
        {
            subjectCode: 'ว21103',
            subject: 'วิทยาศาสตร์2',
            variant: 'green',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 3 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 3 },
            ],
            totalPeriods: 6,
        },
    ],
    'T024': [
        {
            subjectCode: 'ว21103',
            subject: 'วิทยาศาสตร์2',
            variant: 'green',
            assignments: [
                { classCode: '1/3', room: 'C106', periodsPerWeek: 3 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 3 },
            ],
            totalPeriods: 6,
        },
        {
            subjectCode: 'ว32202',
            subject: 'คลื่นแสง',
            variant: 'red',
            assignments: [
                { classCode: '5/4', room: '', periodsPerWeek: 4 },
                { classCode: '5/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 8,
        },
    ],
    'T025': [
        {
            subjectCode: 'ว32202',
            subject: 'คลื่นแสง',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 4 },
                { classCode: '5/2', room: '', periodsPerWeek: 4 },
                { classCode: '5/3', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ว32283',
            subject: 'การสื่อสารวิทยาศาสตร์ในยุคดิจิทัล',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/2', room: 'A316', periodsPerWeek: 3 },
                { classCode: '5/3', room: 'A316', periodsPerWeek: 3 },
            ],
            totalPeriods: 9,
        },
    ],
    'T026': [
        {
            subjectCode: 'ว22202',
            subject: 'โครงงานและนวัตกรรม2',
            variant: 'red',
            assignments: [
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ว31201',
            subject: 'กลศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 4 },
                { classCode: '4/2', room: '', periodsPerWeek: 4 },
                { classCode: '4/3', room: '', periodsPerWeek: 4 },
                { classCode: '4/4', room: '', periodsPerWeek: 4 },
                { classCode: '4/5', room: '', periodsPerWeek: 4 },
            ],
            totalPeriods: 20,
        },
    ],
    'T027': [
        {
            subjectCode: 'ว31283',
            subject: 'สัมมนาทางวิทยาศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '4/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 2,
        },
        {
            subjectCode: 'ว33103',
            subject: 'ฟิสิกส์พื้นฐาน',
            variant: 'green',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 3 },
                { classCode: '6/2', room: '', periodsPerWeek: 3 },
                { classCode: '6/3', room: '', periodsPerWeek: 3 },
                { classCode: '6/4', room: '', periodsPerWeek: 3 },
                { classCode: '6/5', room: '', periodsPerWeek: 3 },
            ],
            totalPeriods: 15,
        },
    ],
    'T028': [
        {
            subjectCode: 'อ22202',
            subject: 'ภาษาอังกฤษเพื่อการอภิปรายกลุ่ม',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 1 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 1 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 1 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'อ31102',
            subject: 'ภาษาอังกฤษขั้นกลาง',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 3 },
                { classCode: '4/2', room: '', periodsPerWeek: 3 },
                { classCode: '4/3', room: '', periodsPerWeek: 3 },
                { classCode: '4/4', room: '', periodsPerWeek: 3 },
                { classCode: '4/5', room: '', periodsPerWeek: 3 },
            ],
            totalPeriods: 15,
        },
    ],
    'T029': [
        {
            subjectCode: 'อ32102',
            subject: 'ภาษาอังกฤษบูรณาการ2',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 3 },
                { classCode: '5/2', room: '', periodsPerWeek: 3 },
                { classCode: '5/3', room: '', periodsPerWeek: 3 },
                { classCode: '5/4', room: '', periodsPerWeek: 3 },
                { classCode: '5/5', room: '', periodsPerWeek: 3 },
            ],
            totalPeriods: 15,
        },
        {
            subjectCode: 'อ33203',
            subject: 'พัฒนาการอ่านและการเขียนภาษาอังกฤษเชิงบูรณาการ',
            variant: 'green',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 2 },
                { classCode: '6/2', room: '', periodsPerWeek: 2 },
                { classCode: '6/3', room: '', periodsPerWeek: 2 },
                { classCode: '6/4', room: '', periodsPerWeek: 2 },
                { classCode: '6/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T030': [
        {
            subjectCode: 'อ23102',
            subject: 'ภาษาอังกฤษบูรณาการ2',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 3 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 3 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 3 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
    ],
    'T031': [
        {
            subjectCode: 'อ21102',
            subject: 'ภาษาอังกฤษพื้นฐาน2',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 3 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 3 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 3 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'อ23202',
            subject: 'พัฒนาคำศัพท์',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T032': [
        {
            subjectCode: 'อ21201',
            subject: 'ภาษาอังกฤษเพื่อการสื่อสาร1',
            variant: 'green',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'อ22102',
            subject: 'ภาษาอังกฤษระดับกลาง2',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 3 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 3 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 3 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
    ],
    'T033': [
        {
            subjectCode: 'ท21102',
            subject: 'ภาษาไทย2',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 3 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 3 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 3 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
    ],
    'T034': [
        {
            subjectCode: 'ท23102',
            subject: 'ภาษาในวรรณคดีไทย2',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 3 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 3 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 3 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ท33102',
            subject: 'คุณค่าของภาษาในวรรณคดีไทย2',
            variant: 'red',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 2 },
                { classCode: '6/2', room: '', periodsPerWeek: 2 },
                { classCode: '6/3', room: '', periodsPerWeek: 2 },
                { classCode: '6/4', room: '', periodsPerWeek: 2 },
                { classCode: '6/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T035': [
        {
            subjectCode: 'ท22102',
            subject: 'ภาษาไทย4',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 3 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 3 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 3 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 3 },
            ],
            totalPeriods: 12,
        },
        {
            subjectCode: 'ท31102',
            subject: 'ภาษาไทย2',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 2 },
                { classCode: '4/2', room: '', periodsPerWeek: 2 },
                { classCode: '4/3', room: '', periodsPerWeek: 2 },
                { classCode: '4/4', room: '', periodsPerWeek: 2 },
                { classCode: '4/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T036': [
        {
            subjectCode: 'ท32102',
            subject: 'ภาษาไทย4',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 2 },
                { classCode: '5/2', room: '', periodsPerWeek: 2 },
                { classCode: '5/3', room: '', periodsPerWeek: 2 },
                { classCode: '5/4', room: '', periodsPerWeek: 2 },
                { classCode: '5/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
        {
            subjectCode: 'ท32201',
            subject: 'ภาษาไทยเพื่อการเขียนงานวิชาการ',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 2 },
                { classCode: '5/2', room: '', periodsPerWeek: 2 },
                { classCode: '5/3', room: '', periodsPerWeek: 2 },
                { classCode: '5/4', room: '', periodsPerWeek: 2 },
                { classCode: '5/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T037': [
        {
            subjectCode: 'ว31284',
            subject: 'กิจกรรมแนะแนว',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: '', periodsPerWeek: 1 },
                { classCode: '4/2', room: '', periodsPerWeek: 1 },
                { classCode: '4/3', room: '', periodsPerWeek: 1 },
                { classCode: '4/4', room: '', periodsPerWeek: 1 },
                { classCode: '4/5', room: '', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
        {
            subjectCode: 'ว32283',
            subject: 'กิจกรรมแนะแนว',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/2', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/3', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/4', room: 'A316', periodsPerWeek: 1 },
                { classCode: '5/5', room: 'A316', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
        {
            subjectCode: 'อ33203',
            subject: 'กิจกรรมแนะแนว',
            variant: 'green',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 1 },
                { classCode: '6/2', room: '', periodsPerWeek: 1 },
                { classCode: '6/3', room: '', periodsPerWeek: 1 },
                { classCode: '6/4', room: '', periodsPerWeek: 1 },
                { classCode: '6/5', room: '', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'T038': [
        {
            subjectCode: 'อ21201',
            subject: 'กิจกรรมแนะแนว',
            variant: 'green',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 1 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 1 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 1 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'อ22202',
            subject: 'กิจกรรมแนะแนว',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 1 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 1 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 1 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
        {
            subjectCode: 'อ23202',
            subject: 'กิจกรรมแนะแนว',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 1 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 1 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 1 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 1 },
            ],
            totalPeriods: 4,
        },
    ],
    'T039': [
        {
            subjectCode: 'ศ21102',
            subject: 'ศิลปนาฏดุริยางค์2',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C108-109', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ศ31102',
            subject: 'ทัศนศิลป์และการออกแบบ',
            variant: 'red',
            assignments: [
                { classCode: '4/1', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '4/2', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '4/3', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '4/4', room: 'C108-109', periodsPerWeek: 2 },
                { classCode: '4/5', room: 'C108-109', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T040': [
        {
            subjectCode: 'ศ23102',
            subject: 'ศิลปนาฏดุริยางค์6',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ศ32101',
            subject: 'นาฏศิลป์และดนตรี',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: 'D321', periodsPerWeek: 1 },
                { classCode: '5/2', room: 'D321', periodsPerWeek: 1 },
                { classCode: '5/3', room: 'D321', periodsPerWeek: 1 },
                { classCode: '5/4', room: 'D321', periodsPerWeek: 1 },
                { classCode: '5/5', room: 'D321', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'T041': [
        {
            subjectCode: 'ศ22102',
            subject: 'ศิลปนาฏดุริยางค์4',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'D323', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'D323', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'D323', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'D323', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T042': [
        {
            subjectCode: 'ส32103',
            subject: 'ภูมิศาสตร์',
            variant: 'green',
            assignments: [
                { classCode: '5/1', room: '', periodsPerWeek: 2 },
                { classCode: '5/2', room: '', periodsPerWeek: 2 },
                { classCode: '5/3', room: '', periodsPerWeek: 2 },
                { classCode: '5/4', room: '', periodsPerWeek: 2 },
                { classCode: '5/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 10,
        },
    ],
    'T043': [
        {
            subjectCode: 'ส21104',
            subject: 'ศาสนา1',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ส33102',
            subject: 'ศาสนา3',
            variant: 'red',
            assignments: [
                { classCode: '6/4', room: '', periodsPerWeek: 2 },
                { classCode: '6/5', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 4,
        },
    ],
    'T044': [
        {
            subjectCode: 'ส21103',
            subject: 'สังคมศึกษา2',
            variant: 'green',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ส33102',
            subject: 'ศาสนา3',
            variant: 'red',
            assignments: [
                { classCode: '6/1', room: '', periodsPerWeek: 2 },
                { classCode: '6/2', room: '', periodsPerWeek: 2 },
                { classCode: '6/3', room: '', periodsPerWeek: 2 },
            ],
            totalPeriods: 6,
        },
    ],
    'T045': [
        {
            subjectCode: 'ส22103',
            subject: 'สังคมศึกษา4',
            variant: 'green',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ส23104',
            subject: 'ประวัติศาสตร์3',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T046': [
        {
            subjectCode: 'ส22104',
            subject: 'ประวัติศาสตร์',
            variant: 'red',
            assignments: [
                { classCode: '2/1', room: 'C212', periodsPerWeek: 2 },
                { classCode: '2/2', room: 'C213', periodsPerWeek: 2 },
                { classCode: '2/3', room: 'C217', periodsPerWeek: 2 },
                { classCode: '2/4', room: 'C218', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'ส23104',
            subject: 'สังคมศึกษา6',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'B103', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'B104', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'B106', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'B107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
    ],
    'T047': [
        {
            subjectCode: 'พ23102',
            subject: 'สุขศึกษาและพลศึกษา6',
            variant: 'red',
            assignments: [
                { classCode: '3/1', room: 'D316', periodsPerWeek: 2 },
                { classCode: '3/2', room: 'D316', periodsPerWeek: 2 },
                { classCode: '3/3', room: 'D316', periodsPerWeek: 2 },
                { classCode: '3/4', room: 'D316', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'พ32102',
            subject: 'สุขศึกษาและพลศึกษา4',
            variant: 'red',
            assignments: [
                { classCode: '5/1', room: 'C101-102', periodsPerWeek: 1 },
                { classCode: '5/2', room: 'C101-102', periodsPerWeek: 1 },
                { classCode: '5/3', room: 'C101-102', periodsPerWeek: 1 },
                { classCode: '5/4', room: 'C101-102', periodsPerWeek: 1 },
                { classCode: '5/5', room: 'C101-102', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
    'T048': [
        {
            subjectCode: 'พ21102',
            subject: 'สุขศึกษาและพลศึกษา2',
            variant: 'red',
            assignments: [
                { classCode: '1/1', room: 'C103', periodsPerWeek: 2 },
                { classCode: '1/2', room: 'C104', periodsPerWeek: 2 },
                { classCode: '1/3', room: 'C106', periodsPerWeek: 2 },
                { classCode: '1/4', room: 'C107', periodsPerWeek: 2 },
            ],
            totalPeriods: 8,
        },
        {
            subjectCode: 'พ33102',
            subject: 'สุขศึกษาและพลศึกษา6',
            variant: 'red',
            assignments: [
                { classCode: '6/1', room: 'D316', periodsPerWeek: 1 },
                { classCode: '6/2', room: 'D316', periodsPerWeek: 1 },
                { classCode: '6/3', room: 'D316', periodsPerWeek: 1 },
                { classCode: '6/4', room: 'D316', periodsPerWeek: 1 },
                { classCode: '6/5', room: 'D316', periodsPerWeek: 1 },
            ],
            totalPeriods: 5,
        },
    ],
};
